FORMAT: 1A
HOST: https://api.lyrics.ovh/v1

# lyrics.ovh

Simple API to retrieve the lyrics of a song.

## Lyrics of a song [/{artist}/{title}]

+ Parameters
    + artist: `Coldplay` (string) - Name of the artist
    + title: `Adventure of a Lifetime` (string) - Title of the song

### Search [GET]

+ Response 200 (application/json)

        {
            "lyrics": "Here the lyrics of the song"
        }

+ Response 404 (application/json)

        {
            "error": "No lyrics found"
        }
        
        https://api.lyrics.ovh/v1/artist=Coldplay&title=Adventure of a Lifetime
        
        https://api.lyrics.ovh/v1/Coldplay/Adventure of a Lifetime
        
        ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        
        https://musicbrainz.org/ws/2/.
        
        /ws/2/area
 /ws/2/artist            recordings, releases, release-groups, works
 /ws/2/collection        user-collections (includes private collections, requires authentication)
 /ws/2/event
 /ws/2/genre
 /ws/2/instrument
 /ws/2/label             releases
 /ws/2/place
 /ws/2/recording         artists, releases, isrcs, url-rels
 /ws/2/release           artists, collections, labels, recordings, release-groups
 /ws/2/release-group     artists, releases
 /ws/2/series
 /ws/2/work
 /ws/2/url
 
 
        
